# Generated by Django 4.2.10 on 2024-03-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="order",
            field=models.IntegerField(null=True),
        ),
    ]
